//
//  ClipboardHistoryStore.swift
//  Snippet Manager
//

import AppKit
import Combine
import Foundation

/// クリップボード履歴の監視・保持・永続化（Clipy 互換仕様）
///
/// - `NSPasteboard.general` の `changeCount` を 0.75 秒間隔でポーリング
/// - 同一内容は先頭へ移動（重複保持しない）
/// - パスワードマネージャ等が宣言する秘匿・一時ペーストボードは記録しない
/// - JSON ファイル（Application Support）へ永続化し再起動後も履歴を復元
@MainActor
final class ClipboardHistoryStore: ObservableObject {
  static let shared = ClipboardHistoryStore()

  @Published private(set) var items: [ClipItem] = []

  /// 履歴の最大保存件数（Clipy デフォルト: 30）
  @Published var maxHistorySize: Int {
    didSet {
      let clamped = Self.clamp(maxHistorySize, range: Self.maxHistorySizeRange)
      if clamped != maxHistorySize {
        maxHistorySize = clamped
        return
      }
      defaults.set(maxHistorySize, forKey: Self.maxHistorySizeKey)
      trimAndSave()
    }
  }

  /// メニュー直下にインライン表示する件数（Clipy デフォルト: 10）
  @Published var inlineItemCount: Int {
    didSet {
      let clamped = Self.clamp(inlineItemCount, range: Self.inlineItemCountRange)
      if clamped != inlineItemCount {
        inlineItemCount = clamped
        return
      }
      defaults.set(inlineItemCount, forKey: Self.inlineItemCountKey)
    }
  }

  /// インライン表示を超えた分をまとめるフォルダあたりの件数（Clipy デフォルト: 10）
  @Published var itemsPerFolder: Int {
    didSet {
      let clamped = Self.clamp(itemsPerFolder, range: Self.itemsPerFolderRange)
      if clamped != itemsPerFolder {
        itemsPerFolder = clamped
        return
      }
      defaults.set(itemsPerFolder, forKey: Self.itemsPerFolderKey)
    }
  }

  static let maxHistorySizeRange = 1...100
  static let inlineItemCountRange = 0...20
  static let itemsPerFolderRange = 1...20

  private static let maxHistorySizeKey = "clipboardMaxHistorySize"
  private static let inlineItemCountKey = "clipboardInlineItemCount"
  private static let itemsPerFolderKey = "clipboardItemsPerFolder"

  private static let defaultMaxHistorySize = 30
  private static let defaultInlineItemCount = 10
  private static let defaultItemsPerFolder = 10

  /// Clipy と同じポーリング間隔
  private static let pollingInterval: TimeInterval = 0.75

  /// http://nspasteboard.org — 秘匿・一時・自動生成データのマーカー型
  private static let ignoredPasteboardTypes: Set<String> = [
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
  ]

  private let defaults = UserDefaults.standard
  private var timer: Timer?
  private var lastChangeCount: Int

  private init() {
    maxHistorySize = Self.readSetting(
      key: Self.maxHistorySizeKey,
      default: Self.defaultMaxHistorySize,
      range: Self.maxHistorySizeRange
    )
    inlineItemCount = Self.readSetting(
      key: Self.inlineItemCountKey,
      default: Self.defaultInlineItemCount,
      range: Self.inlineItemCountRange
    )
    itemsPerFolder = Self.readSetting(
      key: Self.itemsPerFolderKey,
      default: Self.defaultItemsPerFolder,
      range: Self.itemsPerFolderRange
    )

    // 起動時点のペーストボード内容は「起動前のコピー」なので取り込まない
    lastChangeCount = NSPasteboard.general.changeCount

    load()
  }

  // MARK: - Monitoring

  /// ポーリング監視を開始（多重開始は無視）
  func startMonitoring() {
    guard timer == nil else { return }

    let timer = Timer(timeInterval: Self.pollingInterval, repeats: true) { _ in
      Task { @MainActor in
        ClipboardHistoryStore.shared.checkPasteboard()
      }
    }
    // メニュー表示中（イベントトラッキング中）も監視を継続する
    RunLoop.main.add(timer, forMode: .common)
    self.timer = timer
  }

  func stopMonitoring() {
    timer?.invalidate()
    timer = nil
  }

  private func checkPasteboard() {
    let pasteboard = NSPasteboard.general
    guard pasteboard.changeCount != lastChangeCount else { return }
    lastChangeCount = pasteboard.changeCount

    let types = pasteboard.types?.map(\.rawValue) ?? []
    guard Self.ignoredPasteboardTypes.isDisjoint(with: types) else { return }

    guard let text = pasteboard.string(forType: .string), !text.isEmpty else { return }

    record(text: text)
  }

  /// 履歴へ追加。同一内容が既にあれば先頭へ移動（Clipy と同じ重複排除）
  private func record(text: String) {
    items.removeAll { $0.content == text }
    items.insert(ClipItem(content: text), at: 0)
    trimAndSave()
  }

  // MARK: - Query / Mutation

  func item(id: UUID) -> ClipItem? {
    items.first { $0.id == id }
  }

  func clearHistory() {
    items = []
    save()
  }

  private func trimAndSave() {
    if items.count > maxHistorySize {
      items = Array(items.prefix(maxHistorySize))
    }
    save()
  }

  // MARK: - Persistence

  private static var storageURL: URL {
    let base = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
    return base
      .appendingPathComponent("Snippet Manager", isDirectory: true)
      .appendingPathComponent("clipboard-history.json")
  }

  private func load() {
    guard let data = try? Data(contentsOf: Self.storageURL),
          let decoded = try? JSONDecoder().decode([ClipItem].self, from: data)
    else { return }
    items = Array(decoded.prefix(maxHistorySize))
  }

  private func save() {
    let url = Self.storageURL
    do {
      try FileManager.default.createDirectory(
        at: url.deletingLastPathComponent(),
        withIntermediateDirectories: true
      )
      let data = try JSONEncoder().encode(items)
      try data.write(to: url, options: .atomic)
    } catch {
      NSLog("ClipboardHistoryStore: failed to save history: \(error.localizedDescription)")
    }
  }

  // MARK: - Helpers

  private static func readSetting(key: String, default defaultValue: Int, range: ClosedRange<Int>) -> Int {
    guard UserDefaults.standard.object(forKey: key) != nil else { return defaultValue }
    return clamp(UserDefaults.standard.integer(forKey: key), range: range)
  }

  private static func clamp(_ value: Int, range: ClosedRange<Int>) -> Int {
    min(max(value, range.lowerBound), range.upperBound)
  }
}
